Adjust make-release to git.

diff --git a/admin/make-release b/admin/make-release
--- a/admin/make-release
+++ b/admin/make-release
@@ -31,38 +31,40 @@ signexe() {
     rm "$1.bak"
 }
 
-
-tmp=`mktemp -dt $repo-build-XXXXXX`
-
-cd $tmp
-echo Working in $tmp
+dotag=0
 if [ "x$1" = "xbranch" ] ; then
+    checkout=HEAD
+    dotag=1
+    # Pre release checks
+    if grep -q '^200[0-9]???? - ' ChangeLog ; then
+        echo 'ChangeLog does not seem to be finalised, aborting!'
+        exit 1
+    fi
     shift
-    rel=RELEASE_`echo -n $version|tr . _`
-    svn cp -m "Tag release $version" svn+ssh://mort/home/svn/$repo/trunk svn+ssh://mort/home/svn/$repo/tags/$rel
-    svn export svn+ssh://mort/home/svn/$repo/tags/$rel $repo-$version
 elif [ "x$1" = "x" ] ; then
-    rel=trunk
-    svn export svn+ssh://mort/home/svn/$repo/trunk $repo-$version
-else
-    version="$1"
+    checkout=HEAD
+else 
+    checkout=$1
+    version=$1
     shift
-    rel=RELEASE_`echo -n $version|tr . _`
-    svn export svn+ssh://mort/home/svn/$repo/tags/$rel $repo-$version
 fi
 
-echo "Creating release $version from $rel"
-
+tmp=`mktemp -dt $repo-build-XXXXXX`
+cd $tmp
+echo Working in $tmp
+echo "Creating release $version from $checkout"
+git clone -l $srcdir $repo-$version
 cd $repo-$version
+git checkout $checkout
+rm -rf .git
+cd ..
+
+echo 'Creating source tarballs...'
+
 
 # Build source package
 ./setup.py sdist --formats=gztar,bztar,zip
 mv dist/* ../
-
-# Submit to PyPi
-if [ "x$1" = "xbranch" ] ; then
-    ./setup.py register
-fi
 
 # Build Windows Python installer
 wine c:\\python25\\python setup.py bdist_wininst
@@ -93,3 +95,12 @@ done
 # We're done
 echo "Release is in $tmp directory"
 ls -lh $tmp
+
+cd "$srcdir"
+
+if [ $dotag -eq 1 ] ; then
+    # Tag the release
+    git tag -m "Tag release $version" "$version"
+    # Submit to PyPi
+    $tmp/$repo-$version/python/setup.py register
+fi
